RESOURCES:
    - NAME: 'deployPDN'
      DESCRIPTION: 'Despliegue a pdn'
      LABELS: 'deployPDN'
      RESERVED_BY: ''
    - NAME: 'deployLab'
      DESCRIPTION: 'Despliegue a labo'
      LABELS: 'deployLab'
      RESERVED_BY: ''
